# Generated by Django 2.2.5 on 2020-06-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ingredient_type', models.CharField(blank=True, choices=[('01base', '01base'), ('02otherbase', '02otherbase'), ('03fruit', '03fruit'), ('04topping', '04topping'), ('05cheese', '05cheese'), ('06premium', '06premium'), ('07dressing', '07dressing')], default='01base', max_length=40, verbose_name='재료타입')),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='재료이름')),
                ('calory', models.DecimalField(decimal_places=2, default=30, help_text='100g당', max_digits=10, verbose_name='칼로리(cal)')),
                ('sugars', models.DecimalField(decimal_places=2, default=0, help_text='당류', max_digits=10, null=True, verbose_name='당류(g)')),
                ('fat', models.DecimalField(decimal_places=2, default=0, help_text='지방', max_digits=10, null=True, verbose_name='지방(g)')),
                ('carbohydrate', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='단수화물', max_digits=10, verbose_name='단수화물(g)')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='단백질', max_digits=10, verbose_name='단백질(g)')),
                ('cholesterol', models.DecimalField(decimal_places=2, default=0, help_text='콜레스테롤', max_digits=10, null=True, verbose_name='콜레스테롤(mg)')),
                ('salt', models.DecimalField(decimal_places=2, default=0, help_text='나트륨', max_digits=10, null=True, verbose_name='나트륨(mg)')),
                ('potassium', models.DecimalField(decimal_places=2, default=0, help_text='칼륨', max_digits=10, null=True, verbose_name='칼륨(mg)')),
                ('dietaryfiber', models.DecimalField(decimal_places=2, default=30, help_text='식이섬유', max_digits=10, null=True, verbose_name='식이섬유(g)')),
                ('weightForCalory', models.DecimalField(decimal_places=2, default=0, help_text='[자동계산,입력X]', max_digits=10, verbose_name='적용칼로리(cal)')),
                ('weightForSugars', models.DecimalField(decimal_places=2, default=0, help_text='중량적용칼로리[자동계산,입력X]', max_digits=10, verbose_name='적용당류(g)')),
                ('weightForFat', models.DecimalField(decimal_places=2, default=0, help_text='중량적용칼로리[자동계산,입력X]', max_digits=10, verbose_name='적용지방(g)')),
                ('weightForCarbohydrate', models.DecimalField(decimal_places=2, default=0, help_text='[자동계산,입력X]', max_digits=10, verbose_name='적용탄수화물(g)')),
                ('weightForProtein', models.DecimalField(decimal_places=2, default=0, help_text='[자동계산,입력X]', max_digits=10, verbose_name='적용단백질(g)')),
                ('weightForCholesterol', models.DecimalField(decimal_places=2, default=0, help_text='[자동계산,입력X]', max_digits=10, verbose_name='적용콜레스테롤(g)')),
                ('weightForSalt', models.DecimalField(decimal_places=2, default=0, help_text='[자동계산,입력X]', max_digits=10, verbose_name='적용나트륨(g)')),
                ('weightForPotassium', models.DecimalField(decimal_places=2, default=0, help_text='[자동계산,입력X]', max_digits=10, verbose_name='적욜칼륨(g)')),
                ('weightForDietaryfiber', models.DecimalField(decimal_places=2, default=0, help_text='[자동계산,입력X]', max_digits=10, verbose_name='적용식이섬유(g)')),
                ('baseprice', models.IntegerField(default=1000, verbose_name='기본가격')),
                ('description', models.TextField(default='양상추는 샐러드로 많이 이용된다. 내용물로는 수분이 전체의 94∼95%를 차지하고, 그 밖에 탄수화물·조단백질·조섬유·비타민C 등이 들어 있다.', null=True, verbose_name='재료설명')),
                ('baseunit', models.DecimalField(decimal_places=2, default=30, max_digits=10, verbose_name='기본중량(g)')),
                ('amount', models.IntegerField(default=1, verbose_name='기본수량')),
                ('instant_order', models.BooleanField(default=True, verbose_name='주문가능')),
                ('photo', models.ImageField(blank=True, upload_to='ingredients_photos')),
            ],
            options={
                'verbose_name': '재료',
                'verbose_name_plural': '재료 모음',
                'ordering': ['ingredient_type'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80, verbose_name='사진이름')),
                ('file', models.ImageField(upload_to='ingredient_photos')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ingredients.Ingredient')),
            ],
            options={
                'verbose_name': '재료 사진',
                'verbose_name_plural': '재료 사진 모음',
            },
        ),
    ]
