# Generated by Django 2.2.5 on 2020-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=140, null=True, verbose_name='주소')),
                ('room', models.CharField(max_length=140, null=True, verbose_name='호수')),
                ('zonecode', models.CharField(max_length=140, null=True, verbose_name='우편번호')),
                ('etc', models.CharField(max_length=200, null=True, verbose_name='추가사항')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
