# Generated by Django 2.2.5 on 2020-06-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fooddiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='음식일기명')),
                ('caption', models.CharField(max_length=200, verbose_name='내용')),
                ('date', models.DateField(null=True, verbose_name='일자')),
            ],
            options={
                'verbose_name': '음식일기',
                'verbose_name_plural': '음식일기',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80, verbose_name='사진이름')),
                ('file', models.ImageField(upload_to='fooddiary_photos')),
                ('salad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fooddiarys.Fooddiary')),
            ],
            options={
                'verbose_name': '음식일기사진',
                'verbose_name_plural': '음식일기사진',
            },
        ),
    ]
