# Generated by Django 2.2.5 on 2020-06-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=40, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='policy',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='개인정보처리방침'),
        ),
        migrations.AlterField(
            model_name='user',
            name='servicepolicy',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='서비스이용약관'),
        ),
    ]
