# Generated by Django 2.2.5 on 2020-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.IntegerField(null=True, verbose_name='우편번호')),
            ],
            options={
                'verbose_name': '주문가능지역',
                'verbose_name_plural': '주문가능지역',
            },
        ),
    ]
