# Generated by Django 2.2.5 on 2020-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruitbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='과일박스')),
                ('description', models.TextField(blank=True, null=True, verbose_name='과일박스설명')),
                ('photo', models.ImageField(blank=True, upload_to='fruitbox_photos')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='fruitBox', to='ingredients.Ingredient', verbose_name='재료')),
            ],
            options={
                'verbose_name': '과일박스',
                'verbose_name_plural': '과일박스',
            },
        ),
    ]
